### ISSUE TITLE
Task 01: Expand Variables

### ISSUE THREAD

**Issue by robin-wang** [wengxyu1030/DHS-Recode-VII#24]
Create variables, to be in line with MICS6

- [x] w_married : Marrital Status - 1 if woman and mother currently married or living in union, 0 otherwise [MICS6 4 sexual health]
v501 in DHS, have it for both women and child level observations
- DW : DHS coded in 4_sexual_health; data from ind.

- [x] c_vaczero - Child did not receive any vaccination [MICS6 Vaccination]
Child did not receive any vaccinations: gen c_vaczero = (c_measles == 0 & c_polio1 == 0 & c_polio2 == 0 & c_polio3 == 0 & c_bcg == 0 & c_dtp1 == 0 & c_dtp2 == 0 & c_dtp3 == 0) ; forvar c_measles c_polio1 c_polio2 c_polio3 c_bcg c_dtp1 c_dtp2 c_dtp3: replace c_vaczero = .  if X == . ; label var c_vaczero “1 if child did not receive any vaccinations”
- DW : DHS coded in 7_child_vaccination

- [x] c_motherln : the line number of the mother for each kid [MICS6 9 child anthro]
- DW: DHS , hv112 in hm data; implemented in 9_child_anthropometrics

[REMOVED- [x] c_stuund - Child under five both stunted and underweight [MICS6 9 child anthropo]
Child under five both stunted and underweight, i.e.: gen c_stuund = (c_stunted == 1 & c_underweight ==1) ; replace c_stunted == . if c_stunted == . | c_underweight == . ; label var c_sttund “1 if child both stunted and underweight”
- DW: DHS implemented in 9_child_anthropometrics]

- [x] c_wfa : Weight-for-age z-score from survey (original variable) [MICS6 9 child anthropo]
rename hc71 to c_wfa
- [x] c_hfa: Height-for-age z-score from survey (original variable) [MICS6 9 child anthropo]
rename hc70 to c_hfa
- [x] c_wfh : Weight-for-hight z-score from survey (original variable) [MICS6 9 child anthropo]

Let’s include the weight-for-age and height-for-age z-scores from MICS and call these variables c_wfa and c_hfa (and rename hc70 and hc71 in the DHS datasets accordingly). Let’s also add the weight-for-height scores from both surveys, naming them c_wfh.
DW: rename actions undertaken in Master file directly before quality control
use hc72 from hm data, edited in 9_child_anthropometrics, renamed directly before quality control

- [x] hm_birthorder : Birth order [MICS6 10 child mortality]
bord in DHS
- DW: data in birth, implemented in 10_child_mortality

- [x] c_magebrt : age of the mother at the child’s birth [MICS6 10 child mortality]
No indications or instructions for DHS...
- DW: v212 age at first birth? v012 respondents' current age; child's age in months hw1; v012 in birth for respondent's current age
- implemented in 10_child_mortality, based on hw1 and v012

- [x] hh_religion : Religion of woman and mother (v130 in DHS woman and hc1a MICS household dataset) [MICS6 15 household] 
have it for both women and children level observations
- DW: for DHS, use birth data (also available in ind data, but a subset) v130 variable; implemented in 15_household, as birth data is merged into hm data prior to engaging 15_household.

- [x] hh_watersource: Water source (hv201 in DHS HH dataset, already coded for MICS) [MICS6 20 hh sanitation]
- DW: for DHS, data in hh, hv201; implemented in 15_household. As this is coded in hh, variable renamed as hh_watersource, double h
- [x] hh_toilet: Toilet type (hv205 “”, already coded for MICS) [20 hh sanitation]
- DW: for DHS, data in hh, hv205; implemented in 15_household. As this is coded in hh, variable renamed as hh_toilet, double h

- [x] Labels [Lab_var.do]
- [x] Master File keep statements and the like (just to make sure the edited vars are there in the final micro dataset)

**Comment by robin-wang** [comment]
RW implemented on 04 Nov, to be tested.

**Comment by robin-wang** [comment]
Update 1106:
To be further updated per new implementation on mics6

**Comment by robin-wang** [comment]
@wengxyu1030 Here is the issue we used for additional vars. 
The list in label_var.do is most comprehensive:https://github.com/wengxyu1030/DHS-Recode-VII/blob/master/Label_var.do

I select and paste the additional ones we added below:

label var c_anc_pub "15-49y among ANC users had antenatal care in public facilities"
label var c_anc_hosp "15-49y among ANC users had antenatal care in hospital setting"

label var c_underweight  "0-4y WfA <-2 std.dev. from median (WHO) (1/0)"
label var c_stunted  "0-4y HfA <-2 std.dev. from median (WHO) (1/0)"
label var c_wasted  "0-4y WfH <-2 std.dev. from median (WHO) (1/0)"
label var c_underweight_sev  "0-4y WfA <-3 std.dev. from median (WHO) (1/0)"
label var c_stunted_sev  "0-4y HfA <-3 std.dev. from median (WHO) (1/0)"
label var c_wasted_sev  "0-4y WfH <-3 std.dev. from median (WHO) (1/0)"

		label var w_married "Marital Status"
		label var c_vaczero "Child: Not Received Any Vaccination"
		label var c_stu_was "Child: Child under five both stunted and wasted"
		label var c_stu_was_sev "Child: Child under five both severely stunted and severely wasted"
		label var c_motherln "The line number of the mother for each kid"
		label var c_hfa "Child: 0-4y HfA std.dev. from median (WHO), hc70"
		label var c_wfa "Child: 0-4y WfA std.dev. from median (WHO), hc71"
		label var c_wfh "Child: 0-4y WfH std.dev. from median (WHO)"	
		label var hm_birthorder "Birth Order"
		label var c_magebrt "Age of the mother at the child’s birth, based on hw1 and v012"
		cap label var hh_religion "Head of Household Religion"
		label var hh_watersource "Water Source"
		label var hh_toilet "Toilet type"

**Comment by wengxyu1030** [comment]
Compared the codebook and the data output, below are the new variables added:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/XWeng/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/XWeng/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>


<body link="#0563C1" vlink="#954F72">




---
c_anc_hosp
c_anc_public
c_illness2
c_illtreat2
c_magebrt
c_motherln
c_stu_was
c_stu_was_sev
c_stunted_sev
c_underweight_sev
c_vaczero
c_wasted
c_wasted_sev
hh_country_code
hh_religion
hh_toilet
hh_watersource
hm_birthorder
hvidx
w_mammogram_age
w_mammogram_ref
w_married
w_papsmear_age
w_papsmear_ref



</body>

</html>
