### ISSUE TITLE
Task 03: need to check raw data in Recode VII

### ISSUE THREAD

**Issue by robin-wang** [wengxyu1030/DHS-Recode-VII#27]
Recode VII raw data folder contains more data than the World Bank team has included in their template or in the contract to DW.
Need to work out the scope.
- [x] Which ones are not in the list of validation?
https://docs.google.com/spreadsheets/d/1Pmt-qmT2SNrjHdY9JZ7Z24FVoxDPnarQVSRh7XVB6Ck/edit?usp=sharing

**Comment by wengxyu1030** [comment]
Thanks for raising it up, for the extra surveys that not in the DW template, can be added in the Global file in VII: https://github.com/wengxyu1030/DHS-Recode-VII/blob/deccd212eaaefd574d1d583e2f489b2e085cb8fd/0_GLOBAL.do

**Comment by robin-wang** [comment]
Understood, will add these extra into scope when our rerun of Recode-VII goes into the second round (update additional vars' editing logics per Sven's instructions over the weekend.)
